import json,numpy as np,pandas as pd
from pipeline_lib import load_config
def main():
 cfg=load_config();o=cfg['output_dir'];p=pd.read_csv(o/'protein_unique_table.tsv',sep='\t');m=json.loads((o/'method_metadata.json').read_text());s=json.loads((o/'selected_hdbscan_model.json').read_text())['selected'];met=pd.read_csv(o/'clustering_metrics.tsv',sep='\t');cs=pd.read_csv(o/'cluster_summary.tsv',sep='\t').sort_values('cluster_size',ascending=False);pc=pd.read_csv(o/'pca_explained_variance.tsv',sep='\t')
 lines=['# MemPro protein representation and unsupervised clustering report','', '## Dataset',f'- Unique canonical proteins: {len(p):,}',f'- Proteins with non-Unknown target annotation: {(p.target_class != "Unknown").sum():,}',f'- Sequence length median (range): {p.sequence_length.astype(float).median():.0f} ({p.sequence_length.astype(float).min():.0f}–{p.sequence_length.astype(float).max():.0f})','', '## Representation',f'- Model: {m["model_name"]}',f'- Protein embedding dimension: {m["embedding_dimension"]}',f'- Pooling: {m["pooling_method"]}','', '## PCA',f'- PCs used: {len(pc)}',f'- Cumulative variance at final PC: {pc.cumulative_explained_variance.iloc[-1]:.3f}','', '## Unsupervised HDBSCAN',f'- Parameters: min_cluster_size={s["min_cluster_size"]}; min_samples={s["min_samples"]}',f'- Clusters: {int(s["n_clusters"])}; noise fraction: {float(s["noise_fraction"]):.3f}; silhouette (non-noise): {float(s["silhouette_non_noise"]):.3f}','','## Post-hoc agreement with existing target classes']
 for _,r in met.iterrows():lines.append(f'- {r.metric}: {float(r.value):.3f}' if isinstance(r.value,(int,float,np.number)) else f'- {r.metric}: {r.value}')
 lines += ['', '## Major clusters (post-hoc labels only)']
 for _,r in cs.head(15).iterrows(): lines.append(f'- Cluster {r.cluster_id}: n={r.cluster_size}; dominant class={r.dominant_target_class}; purity={r.cluster_purity:.1%}')
 lines += ['', '## Interpretation boundary','- HDBSCAN used PCA embeddings, not UMAP coordinates. UMAP is a visualization only.','- Target classes were not supplied to embedding, PCA, UMAP, or HDBSCAN. ARI/NMI and purity are post-hoc annotation agreement measures.','- If ARI/NMI and cluster purity are low, this is reported as weak label separation rather than tuned away.']
 (o/'PROTEIN_CLUSTERING_REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
if __name__=='__main__':main()
